project:
  type: book

book:
  title: "CrossGo"
  author: "Métrika Group"
  date: "2023"
  chapters:
    - index.qmd
    - intro.qmd
    - register.qmd
    - site.qmd
    - campaña.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

